const Binance = require('binance-api-node').default;
const db = require('../services/db');
const cryptoService = require('../services/cryptoService');

const runners = new Map();
let schemaReady = false;

const STABLECOINS = new Set(['USDT','USDC','FDUSD','TUSD','DAI','BUSD','USD','USD1','RLUSD','EUR','TRY','BRL','GBP','AUD']);
const BLOCKED = new Set(['TRX']);
const LEVERAGED_SUFFIXES = ['UP','DOWN','BULL','BEAR'];
const STRATEGIES = {
  basico: {
    name:'Básico',
    description:'Mais oportunidades; filtros técnicos essenciais.',
    mode:'volume',
    scoreMin:5,
    rsiMin:40,
    rsiMax:65,
    requirePullback:false,
    marketMinScore:0
  },
  medio: {
    name:'Médio',
    description:'Equilíbrio entre seletividade e frequência.',
    mode:'volume',
    scoreMin:6,
    rsiMin:45,
    rsiMax:60,
    requirePullback:false,
    marketMinScore:0
  },
  premium: {
    name:'Premium',
    description:'Filtros de tendência e mercado; maior seletividade.',
    mode:'marketcap',
    scoreMin:7,
    rsiMin:40,
    rsiMax:65,
    requirePullback:false,
    marketMinScore:2
  },
  avancado: {
    name:'Avançado',
    description:'Mais seletivo; exige confirmação adicional do mercado.',
    mode:'marketcap',
    scoreMin:8,
    rsiMin:45,
    rsiMax:62,
    requirePullback:false,
    marketMinScore:3
  },
  elite: {
    name:'Elite',
    description:'Máxima seletividade; foco em setups mais filtrados.',
    mode:'marketcap',
    scoreMin:9,
    rsiMin:48,
    rsiMax:58,
    requirePullback:true,
    marketMinScore:4
  }
};
function strategyInfo(version){
  return STRATEGIES[String(version||'premium')] || STRATEGIES.premium;
}


function num(v){ const n=Number(v); return Number.isFinite(n)?n:0; }
function sleep(ms){ return new Promise(r=>setTimeout(r,ms)); }
function isStable(a){ return STABLECOINS.has(String(a||'').toUpperCase()); }
function isLeveraged(a){ const s=String(a||'').toUpperCase(); return LEVERAGED_SUFFIXES.some(x=>s.endsWith(x)); }
function roundDown(v, step){ if(!(v>0)||!(step>0)) return 0; const p=Math.max(0,(String(step).split('.')[1]||'').length); return Number((Math.floor(v/step)*step).toFixed(p)); }
function roundPrice(v,tick){ return roundDown(v,tick); }
function ema(values,period){ if(values.length<period)return null; let x=values.slice(0,period).reduce((a,b)=>a+num(b),0)/period; const k=2/(period+1); for(let i=period;i<values.length;i++) x=(num(values[i])-x)*k+x; return x; }
function rsi(values,period=14){ if(values.length<period+1)return null; let g=0,l=0; for(let i=values.length-period;i<values.length;i++){const d=num(values[i])-num(values[i-1]); if(d>0)g+=d; else l-=d;} if(l===0)return 100; return 100-100/(1+g/l); }
function errText(e){ return e?.body ? (typeof e.body==='string'?e.body:JSON.stringify(e.body)) : (e?.message||String(e)); }

async function ensureSchema(){
  if(schemaReady)return;

  // IMPORTANTE:
  // Estas tabelas podem ter sido criadas por versões anteriores do robô.
  // CREATE TABLE IF NOT EXISTS NÃO atualiza tabelas existentes.
  // Por isso fazemos uma migração compatível, adicionando somente as colunas
  // que estiverem faltando.

  await db.query(`
    CREATE TABLE IF NOT EXISTS robot_configs (
      user_id INTEGER NOT NULL,
      account_id INTEGER NOT NULL,
      strategy_version VARCHAR(40) NOT NULL DEFAULT 'v7.1',
      entry_percent NUMERIC(8,3) NOT NULL DEFAULT 98,
      take_profit NUMERIC(8,3) NOT NULL DEFAULT 5,
      stop_loss NUMERIC(8,3) NOT NULL DEFAULT 2.5,
      stop_loss_active BOOLEAN NOT NULL DEFAULT true,
      max_operations INTEGER NOT NULL DEFAULT 3,
      interval VARCHAR(8) NOT NULL DEFAULT '15m',
      max_coins INTEGER NOT NULL DEFAULT 20,
      running BOOLEAN NOT NULL DEFAULT false,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      PRIMARY KEY(user_id,account_id)
    );

    CREATE TABLE IF NOT EXISTS robot_operations (
      id BIGSERIAL PRIMARY KEY,
      user_id INTEGER NOT NULL,
      account_id INTEGER NOT NULL,
      symbol VARCHAR(30) NOT NULL,
      buy_order_id VARCHAR(80),
      tp_order_id VARCHAR(80),
      buy_price NUMERIC(30,12),
      quantity NUMERIC(30,12),
      tp_price NUMERIC(30,12),
      stop_price NUMERIC(30,12),
      status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
      opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      closed_at TIMESTAMPTZ,
      close_reason VARCHAR(30),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    -- Migração de robot_configs de versões antigas.
    ALTER TABLE robot_configs
      ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
      ADD COLUMN IF NOT EXISTS strategy_version VARCHAR(40) NOT NULL DEFAULT 'v7.1',
      ADD COLUMN IF NOT EXISTS entry_percent NUMERIC(8,3) NOT NULL DEFAULT 98,
      ADD COLUMN IF NOT EXISTS take_profit NUMERIC(8,3) NOT NULL DEFAULT 5,
      ADD COLUMN IF NOT EXISTS stop_loss NUMERIC(8,3) NOT NULL DEFAULT 2.5,
      ADD COLUMN IF NOT EXISTS stop_loss_active BOOLEAN NOT NULL DEFAULT true,
      ADD COLUMN IF NOT EXISTS max_operations INTEGER NOT NULL DEFAULT 3,
      ADD COLUMN IF NOT EXISTS interval VARCHAR(8) NOT NULL DEFAULT '15m',
      ADD COLUMN IF NOT EXISTS max_coins INTEGER NOT NULL DEFAULT 20,
      ADD COLUMN IF NOT EXISTS running BOOLEAN NOT NULL DEFAULT false,
      ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

    -- Migração de robot_operations de versões antigas.
    ALTER TABLE robot_operations
      ADD COLUMN IF NOT EXISTS buy_order_id VARCHAR(80),
      ADD COLUMN IF NOT EXISTS tp_order_id VARCHAR(80),
      ADD COLUMN IF NOT EXISTS buy_price NUMERIC(30,12),
      ADD COLUMN IF NOT EXISTS quantity NUMERIC(30,12),
      ADD COLUMN IF NOT EXISTS tp_price NUMERIC(30,12),
      ADD COLUMN IF NOT EXISTS stop_price NUMERIC(30,12),
      ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
      ADD COLUMN IF NOT EXISTS opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
      ADD COLUMN IF NOT EXISTS close_reason VARCHAR(30),
      ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

    CREATE INDEX IF NOT EXISTS idx_robot_ops_user_account_status
      ON robot_operations(user_id,account_id,status);

    CREATE INDEX IF NOT EXISTS idx_robot_configs_user_account
      ON robot_configs(user_id,account_id);
  `);

  // Garante valores padrão em registros antigos que eventualmente tenham
  // ficado NULL durante migrações anteriores.
  await db.query(`
    UPDATE robot_configs
    SET
      strategy_version=COALESCE(strategy_version,'v7.1'),
      entry_percent=COALESCE(entry_percent,98),
      take_profit=COALESCE(take_profit,5),
      stop_loss=COALESCE(stop_loss,2.5),
      stop_loss_active=COALESCE(stop_loss_active,true),
      max_operations=COALESCE(max_operations,3),
      interval=COALESCE(interval,'15m'),
      max_coins=COALESCE(max_coins,20),
      running=COALESCE(running,false),
      updated_at=COALESCE(updated_at,NOW())
  `);

  schemaReady=true;
}
async function getAccount(userId,accountId){
  const r=await db.query(`SELECT id,user_id,name,api_key_encrypted,api_secret_encrypted,active FROM binance_accounts WHERE id=$1 AND user_id=$2`,[accountId,userId]);
  return r.rows[0]||null;
}
function clientFor(account){ return Binance({apiKey:cryptoService.decrypt(account.api_key_encrypted),apiSecret:cryptoService.decrypt(account.api_secret_encrypted),recvWindow:60000}); }

async function getConfig(userId,accountId){
  await ensureSchema();
  const r=await db.query(`SELECT * FROM robot_configs WHERE user_id=$1 AND account_id=$2`,[userId,accountId]);
  return r.rows[0]||null;
}
async function saveConfig(userId,accountId,c){
  await ensureSchema();
  const r=await db.query(`INSERT INTO robot_configs(user_id,account_id,strategy_version,entry_percent,take_profit,stop_loss,stop_loss_active,max_operations,interval,max_coins,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,NOW()) ON CONFLICT(user_id,account_id) DO UPDATE SET strategy_version=EXCLUDED.strategy_version,entry_percent=EXCLUDED.entry_percent,take_profit=EXCLUDED.take_profit,stop_loss=EXCLUDED.stop_loss,stop_loss_active=EXCLUDED.stop_loss_active,max_operations=EXCLUDED.max_operations,interval=EXCLUDED.interval,max_coins=EXCLUDED.max_coins,updated_at=NOW() RETURNING *`,[userId,accountId,c.strategyVersion,c.entryPercent,c.takeProfit,c.stopLoss,c.stopLossActive,c.maxOperations,c.interval,c.maxCoins]);
  return r.rows[0];
}

async function top20(client,exchangeInfo,maxCoins){
  const response=await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=50&page=1&sparkline=false',{headers:{'User-Agent':'CriptoPro/1.0'}});
  if(!response.ok) throw new Error(`CoinGecko HTTP ${response.status}`);
  const coins=await response.json(); const out=[];
  for(const coin of coins){
    if(out.length>=maxCoins)break;
    const base=String(coin.symbol||'').toUpperCase();
    if(!base||isStable(base)||isLeveraged(base)||BLOCKED.has(base))continue;
    const pair=exchangeInfo.symbols.find(s=>s.status==='TRADING'&&s.quoteAsset==='USDT'&&String(s.baseAsset).toUpperCase()===base);
    if(!pair)continue;
    if(pair.onboardDate && Date.now()-Number(pair.onboardDate)<365*86400000)continue;
    out.push({symbol:pair.symbol,baseAsset:base,rank:num(coin.market_cap_rank),name:coin.name});
  }
  return out;
}

async function marketFilter(client){
  try{
    const d=await client.candles({symbol:'BTCUSDT',interval:'1d',limit:250}); const c1=d.slice(0,-1).map(x=>num(x.close));
    if(c1.length<200)return {favoravel:false,quente:false,score:0};
    const e50=ema(c1,50),e200=ema(c1,200),p=c1.at(-1); let score=0;
    if(p>e50)score++; if(e50>e200)score++;
    const d4=await client.candles({symbol:'BTCUSDT',interval:'4h',limit:150}); const c4=d4.slice(0,-1).map(x=>num(x.close));
    const e21=ema(c4,21),e50_4=ema(c4,50),r=rsi(c4,14),p4=c4.at(-1); if(p4>e50_4)score++; if(e21>e50_4)score++;
    const hot=((p4-e21)/e21)>0.04 || r>70;
    return {favoravel:score>=2,quente:hot,score};
  }catch(e){ return {favoravel:false,quente:false,score:0,error:errText(e)}; }
}

async function analyze(client,symbol,market,interval,version='premium'){
  const strategy=strategyInfo(version);
  const rows=await client.candles({symbol,interval,limit:120});
  const closed=rows.slice(0,-1);
  if(closed.length<50)return {valid:false,reason:'Poucos candles'};

  const closes=closed.map(x=>num(x.close));
  const opens=closed.map(x=>num(x.open));
  const highs=closed.map(x=>num(x.high));
  const lows=closed.map(x=>num(x.low));
  const volumes=closed.map(x=>num(x.volume));

  const e9=ema(closes,9),e21=ema(closes,21),r=rsi(closes,14);
  const last=closes.length-1,p=closes[last],o=opens[last];
  let score=0;

  if(e9>e21)score+=2;
  if(r>=strategy.rsiMin&&r<=strategy.rsiMax)score++;
  if(r>strategy.rsiMax+5)return {valid:false,reason:`RSI muito alto: ${r.toFixed(2)}`};

  const dist=(p-e21)/e21;
  if(dist>0.04)return {valid:false,reason:'Preço esticado'};
  if(Math.abs(dist)<=0.025)score++;

  const avgVol=volumes.slice(-21,-1).reduce((a,b)=>a+b,0)/Math.max(1,volumes.slice(-21,-1).length);
  const vr=avgVol?volumes[last]/avgVol:0;
  if(vr>=0.8)score++;
  if(p>o)score++;

  const minLow=Math.min(...lows.slice(-6));
  const pull=Math.abs((minLow-e21)/e21)<=0.025&&p>=e21*0.995&&p<=e21*1.04;
  const maxHigh=Math.max(...highs.slice(-11,-1));
  const breakout=p>maxHigh&&vr>=1.3&&dist<=0.04;

  let entry=null;
  if(pull) { score++; entry='PULLBACK'; }
  else if(breakout && !market.quente) { score++; entry='BREAKOUT'; }

  if(strategy.requirePullback && entry!=='PULLBACK')
    return {valid:false,reason:'Estratégia exige PULLBACK'};

  if(market.quente && entry!=='PULLBACK')
    return {valid:false,reason:'Mercado aquecido'};

  if(market.score < strategy.marketMinScore)
    return {valid:false,reason:`Mercado abaixo do filtro da estratégia (${market.score})`};

  if(score<strategy.scoreMin || !entry)
    return {valid:false,reason:`Score ${score} abaixo de ${strategy.scoreMin}`};

  const price=num((await client.prices({symbol}))[symbol]);
  return {
    valid:price>0,price,score,rsi:r,e9,e21,entry,
    strategy:version,
    reason:price>0?'':'Preço inválido'
  };
}
async function openCount(userId,accountId){ await ensureSchema(); const r=await db.query(`SELECT COUNT(*)::int AS count FROM robot_operations WHERE user_id=$1 AND account_id=$2 AND status='OPEN'`,[userId,accountId]); return num(r.rows[0]?.count); }
async function existingSymbol(userId,accountId,symbol){ await ensureSchema(); const r=await db.query(`SELECT id FROM robot_operations WHERE user_id=$1 AND account_id=$2 AND symbol=$3 AND status='OPEN' LIMIT 1`,[userId,accountId,symbol]); return !!r.rows.length; }

async function buy(userId,account,config,symbol){
  const client=clientFor(account); const info=await client.exchangeInfo(); const si=info.symbols.find(s=>s.symbol===symbol); if(!si)throw new Error('Par não encontrado');
  const lot=si.filters.find(f=>f.filterType==='LOT_SIZE'), pf=si.filters.find(f=>f.filterType==='PRICE_FILTER'), nf=si.filters.find(f=>f.filterType==='NOTIONAL'||f.filterType==='MIN_NOTIONAL');
  const step=num(lot?.stepSize),tick=num(pf?.tickSize),minNot=num(nf?.minNotional); const ac=await client.accountInfo(); const usdt=num(ac.balances.find(b=>b.asset==='USDT')?.free); const price=num((await client.prices({symbol}))[symbol]);
  const value=usdt*(num(config.entry_percent)/100); let qty=roundDown(value/price,step); if(qty<=0||qty*price<minNot)throw new Error('Saldo/valor mínimo insuficiente');
  const order=await client.order({symbol,side:'BUY',type:'MARKET',quantity:qty}); await sleep(1200);
  let executedQty=num(order.executedQty)||qty; let buyValue=num(order.cummulativeQuoteQty)||0; let buyPrice=buyValue>0?buyValue/executedQty:price;
  if(Array.isArray(order.fills)&&order.fills.length){let q=0,v=0; for(const f of order.fills){q+=num(f.qty);v+=num(f.qty)*num(f.price);} if(q>0){executedQty=q;buyPrice=v/q;}}
  const ac2=await client.accountInfo(); const asset=symbol.replace(/USDT$/,''); const free=num(ac2.balances.find(b=>b.asset===asset)?.free); qty=roundDown(Math.min(executedQty,free||executedQty),step); if(qty<=0)throw new Error('Saldo do ativo não encontrado após compra');
  const tp=roundPrice(buyPrice*(1+num(config.take_profit)/100),tick); const stop=roundPrice(buyPrice*(1-num(config.stop_loss)/100),tick);
  const tpOrder=await client.order({symbol,side:'SELL',type:'LIMIT',quantity:qty,price:tp,timeInForce:'GTC'});
  await db.query(`INSERT INTO robot_operations(user_id,account_id,symbol,buy_order_id,tp_order_id,buy_price,quantity,tp_price,stop_price,status,opened_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'OPEN',NOW(),NOW())`,[userId,account.id,symbol,String(order.orderId),String(tpOrder.orderId),buyPrice,qty,tp,stop]);
  return {symbol,buyOrderId:order.orderId,tpOrderId:tpOrder.orderId,buyPrice,quantity:qty,tpPrice:tp,stopPrice:stop};
}

async function monitorOpenOps(userId,account,config){
  const client=clientFor(account); await ensureSchema(); const r=await db.query(`SELECT * FROM robot_operations WHERE user_id=$1 AND account_id=$2 AND status='OPEN' ORDER BY id`,[userId,account.id]);
  for(const op of r.rows){
    try{
      const price=num((await client.prices({symbol:op.symbol}))[op.symbol]);
      if(config.stop_loss_active && price<=num(op.stop_price)){
        try{await client.cancelOrder({symbol:op.symbol,orderId:op.tp_order_id});}catch(_){ }
        const ex=await client.exchangeInfo(); const si=ex.symbols.find(s=>s.symbol===op.symbol); const lot=si?.filters?.find(f=>f.filterType==='LOT_SIZE'); const qty=roundDown(num(op.quantity),num(lot?.stepSize));
        if(qty>0) await client.order({symbol:op.symbol,side:'SELL',type:'MARKET',quantity:qty});
        await db.query(`UPDATE robot_operations SET status='CLOSED',closed_at=NOW(),close_reason='STOP',updated_at=NOW() WHERE id=$1`,[op.id]);
        continue;
      }
      let ord=null; try{ord=await client.getOrder({symbol:op.symbol,orderId:op.tp_order_id});}catch(_){ }
      if(ord && String(ord.status).toUpperCase()==='FILLED'){
        await db.query(`UPDATE robot_operations SET status='CLOSED',closed_at=NOW(),close_reason='TAKE_PROFIT',updated_at=NOW() WHERE id=$1`,[op.id]);
      }
    }catch(e){ console.error(`ROBOT OP ${op.symbol}:`,errText(e)); }
  }
}

async function topVolumePairs(client,maxCoins){
  const tickers=await client.dailyStats();
  return tickers
    .filter(t=>{
      const symbol=String(t.symbol||'').toUpperCase();
      const base=symbol.endsWith('USDT')?symbol.slice(0,-4):'';
      return symbol.endsWith('USDT') && base && !isStable(base) && !isLeveraged(base) && !BLOCKED.has(base);
    })
    .sort((a,b)=>num(b.quoteVolume)-num(a.quoteVolume))
    .slice(0,num(maxCoins));
}

async function scanByProfile(userId,account,config,version){
  const client=clientFor(account);
  const strategy=strategyInfo(version);
  const count=await openCount(userId,account.id);
  if(count>=num(config.max_operations))
    return {message:`Limite de ${config.max_operations} operações atingido`};

  if(strategy.mode==='volume'){
    const pairs=await topVolumePairs(client,num(config.max_coins));
    for(const p of pairs){
      if(await existingSymbol(userId,account.id,p.symbol))continue;

      const rows=await client.candles({symbol:p.symbol,interval:config.interval,limit:100});
      if(!rows||rows.length<50)continue;

      const closes=rows.map(x=>num(x.close));
      const volumes=rows.map(x=>num(x.volume));
      const e9=ema(closes.slice(-20),9);
      const e21=ema(closes.slice(-30),21);
      const r=rsi(closes,14);
      const price=closes.at(-1);
      const volume=volumes.at(-1);
      const avg=volumes.slice(-21,-1).reduce((a,b)=>a+b,0)/20;

      let score=0;
      if(e9>e21)score+=2;
      if(r>=strategy.rsiMin&&r<=strategy.rsiMax)score++;
      if(price>e9)score++;
      if(volume>avg)score++;
      if(price>=e21)score++;

      if(score<strategy.scoreMin)continue;

      const current=await openCount(userId,account.id);
      if(current>=num(config.max_operations))break;

      try{
        return {message:'Operação aberta',operation:await buy(userId,account,config,p.symbol)};
      }catch(e){
        console.error(`ROBOT ${version.toUpperCase()} BUY ${p.symbol}:`,errText(e));
      }
    }
    return {message:'Nenhum setup aprovado'};
  }

  const ex=await client.exchangeInfo();
  const market=await marketFilter(client);
  if(!market.favoravel)return {message:'Mercado não favorável'};
  if(market.score<strategy.marketMinScore)return {message:`Mercado abaixo do filtro da estratégia (${market.score})`};

  const pairs=await top20(client,ex,num(config.max_coins));
  for(const p of pairs){
    if(await existingSymbol(userId,account.id,p.symbol))continue;

    const setup=await analyze(client,p.symbol,market,config.interval,version);
    if(!setup.valid)continue;

    const current=await openCount(userId,account.id);
    if(current>=num(config.max_operations))break;

    try{
      return {message:'Operação aberta',operation:await buy(userId,account,config,p.symbol)};
    }catch(e){
      console.error(`ROBOT ${version.toUpperCase()} BUY ${p.symbol}:`,errText(e));
    }
  }
  return {message:'Nenhum setup aprovado'};
}

async function scanV6(userId,account,config){
  return scanByProfile(userId,account,config,'medio');
}
async function scan(userId,account,config){
  const version=String(config.strategy_version||'premium');

  if(version==='v6')return scanByProfile(userId,account,config,'medio');
  if(STRATEGIES[version])return scanByProfile(userId,account,config,version);

  // Compatibilidade com configurações antigas.
  return scanByProfile(userId,account,config,'premium');
}
async function loop(userId,accountId){
  const key=`${userId}:${accountId}`; if(runners.has(key))return;
  const runner={stop:false}; runners.set(key,runner);
  try{
    while(!runner.stop){
      const account=await getAccount(userId,accountId); const config=await getConfig(userId,accountId); if(!account||!config||!config.running){break;}
      try{ await monitorOpenOps(userId,account,config); await scan(userId,account,config); }catch(e){console.error('ROBOT LOOP:',errText(e));}
      await sleep(15000);
    }
  }finally{runners.delete(key);}
}

async function start(userId,accountId){
  await ensureSchema();

  const account=await getAccount(userId,accountId);
  if(!account)throw new Error('Conta Binance não encontrada');
  if(!account.active)throw new Error('Conta Binance inativa');

  const c=await getConfig(userId,accountId);
  if(!c)throw new Error('Configure o robô antes de iniciar');

  const key=`${userId}:${accountId}`;
  const oldRunner=runners.get(key);

  if(oldRunner){
    oldRunner.stop=true;
    const deadline=Date.now()+20000;
    while(runners.has(key)&&Date.now()<deadline)await sleep(250);
    if(runners.has(key))
      throw new Error('O robô anterior ainda está encerrando. Aguarde alguns segundos e tente novamente.');
  }

  await db.query(
    `UPDATE robot_configs SET running=true,updated_at=NOW()
     WHERE user_id=$1 AND account_id=$2`,
    [userId,accountId]
  );

  console.log(`[ROBO] VERSÃO ${String(c.strategy_version).toUpperCase()} LIGADO | usuário=${userId} | conta=${accountId}`);

  loop(userId,String(accountId));
  await sleep(150);

  const status=await getStatus(userId,accountId);
  if(!status.engineRunning){
    await db.query(`UPDATE robot_configs SET running=false,updated_at=NOW() WHERE user_id=$1 AND account_id=$2`,[userId,accountId]);
    throw new Error('A configuração foi ativada, mas o motor do robô não iniciou.');
  }

  return status;
}
async function stop(userId,accountId){
  await ensureSchema();

  const key=`${userId}:${accountId}`;
  const runner=runners.get(key);
  if(runner)runner.stop=true;

  await db.query(
    `UPDATE robot_configs SET running=false,updated_at=NOW()
     WHERE user_id=$1 AND account_id=$2`,
    [userId,accountId]
  );

  const deadline=Date.now()+20000;
  while(runners.has(key)&&Date.now()<deadline)await sleep(250);

  console.log(`[ROBO] DESLIGADO | usuário=${userId} | conta=${accountId}`);

  return getStatus(userId,accountId);
}
async function resumeRunning(){ await ensureSchema(); const r=await db.query(`SELECT user_id,account_id FROM robot_configs WHERE running=true`); for(const x of r.rows){ console.log(`[ROBO] RETOMADO | usuário=${x.user_id} | conta=${x.account_id}`); loop(x.user_id,String(x.account_id)); } }

async function getStatus(userId,accountId){ await ensureSchema(); const c=await getConfig(userId,accountId); const r=await db.query(`SELECT id,symbol,buy_price,quantity,tp_price,stop_price,status,opened_at,closed_at,close_reason FROM robot_operations WHERE user_id=$1 AND account_id=$2 ORDER BY id DESC LIMIT 20`,[userId,accountId]); const engineRunning=runners.has(`${userId}:${accountId}`); return {success:true,config:c,running:!!c?.running || engineRunning,engineRunning,operations:r.rows}; }

module.exports={ensureSchema,getConfig,saveConfig,start,stop,getStatus,resumeRunning};
